### ISSUE TITLE
[Investigation] Topics/Organization page should have the same proportion of image-description ratio as in the Figma design

### ISSUE THREAD

**Issue by demenech** [FCSCOpendata/frontend#32]
## Acceptance Criteria
- [ ] I can see some conclusions, examples and ideas to fix this.

## Tasks
- [x] Investigate a way to make the header image in the topics/orgs pages taller. An attractive point from the original design is that this image takes up a big portion of the vertical space on the screen.

**Comment by demenech** [comment]
How the image header currently looks like on a 1440x927 monitor:
![ss-2022-08-27-10:30:11](https://user-images.githubusercontent.com/16550934/187032543-436df86c-20a4-4a62-9d8b-137b393e5ac5.png)
  
How the mocks look like in a 1080p monitor: 
![ss-2022-08-27-10:36:12](https://user-images.githubusercontent.com/16550934/187032640-f9a83aac-69fb-423e-8ad8-bf878ab46a40.png)
  
In the mocks it's easy to calculate that the image is taking 920/1080=~47% of the screen width.  
The portal, under similar circumstances (1080p monitor), displays the image as taking part of 848/1080=~44% of the screen width.  
The portal, on a 1440x927 monitor, displays the image as taking part of 608/1440=~42% of the screen width.
  
My suggestion to increase the similarity between the design and the result is to simply adjust the proportion between the two parts of the header, therefore increasing the height of the image as well.  
The results:
1440x927
![ss-2022-08-27-14:30:03](https://user-images.githubusercontent.com/16550934/187041427-02b9b06a-ec67-4aa2-a170-1f6634aa95e6.png)

  
1920x1080
![ss-2022-08-27-14:27:56](https://user-images.githubusercontent.com/16550934/187041360-696e679f-d187-4b96-9fec-3e0cc64fe8e9.png)
  
1280x720
![ss-2022-08-27-14:27:50](https://user-images.githubusercontent.com/16550934/187041368-2ff05fde-9ba3-4e22-96f8-b5b563b61366.png)

**Comment by juanbrits** [comment]
@demenech please merge and deploy as discussed in today's standup.
