### ISSUE TITLE
[Investigation] i18n Arabic Translation Integration

### ISSUE THREAD

**Issue by steveoni** [FCSCOpendata/frontend#33]
Investigate an approach to which Arabic translation can be easily managed and integrated into the portal

## Investigation

The goal is we want to have a single channel to which Arabic translation can be added, which then triggers GitHub action to build the app with the new additional translation.

The two most popular next.js package used to manage i18n are `next-i18next` and `next-translate`. Both packages offer almost the same apis.

### Next-i18next

Declare translation folders
```
.
└── public
    └── locales
        ├── en
        |   └── common.json
        └── ar
            └── common.json
```

`common.json` contains a mapping for text and their translation e.g

```
# en/common.json

{
    "welcome-note": "Welcome to the world of UAE Open Data!",
    .   .   .    .   .   .
}

# ar/common.json

{
    "welcome-note": " في الإمارات!  أهلا بكم في عالم البيانات المفتوحة" 
}
```

To enable translation: we wrap our app with next-i18next provider in `.__app.js`

```js
// __app.js
import { appWithTranslation } from 'next-i18next'

 .    .    .    .    .    .    .    .    .

export default appwithTranslation(App)
```

To translate any text

```js
//about page

import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'


const About = () => {
    const { t } = useTranslation('common')
    return <div>{t('welcome-note')} </div>
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['common']),
  },
})

```
That's all for enabling the translation and also need to set the default locale in the config

```js
// next-18next.config.js
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ar'],
  }
}

//next-config
const { i18n } = require('./next-i18next.config');

module.exports = {
  i18n,
};
```

## next-translate

same approach with `next-i18next`, just that the `locales folder is not stored in `/public`

```
.
└── locales
        ├── en
        |   └── common.json
        └── ar
            └── common.json
```

set common.json
```
# en/common.json

{
    "welcome-note": "Welcome to the world of UAE Open Data!",
    .   .   .    .   .   .
}

# ar/common.json

{
    "welcome-note": " في الإمارات!  أهلا بكم في عالم البيانات المفتوحة" 
}
```

To translate we can decide not to add a provider to `__app.js` and just go ahead to translate (though Provider is also available we might need it on only rare cases as suggested here https://www.npmjs.com/package/next-translate#i18nprovider:~:text=))%0A%7D-,I18nProvider,-Size%3A%20~3kb%20%F0%9F%93%A6 )

```js
//about page

import useTranslation from 'next-translate/useTranslation'


const About = () => {
    const { t } = useTranslation('common')
    return <div>{t('welcome-note')} </div>
}

```
In Next-translate we don't need to declare getStaticProps, it is added by default.  `getStaticProps` is used to add `namespace` for the required translated file in `next-i18next` but in `next-translate` namespace is already added once in the config.

```

// i18n.json
{
  "locales": ["en", "ar"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"],
  }
}

//next.config.js
const nextTranslate = require('next-translate')

module.exports = nextTranslate()
```

## conclusion

* `Next-translate` seems to prevent adding extra lines of codes in _app.js and `getStaticProps` to all page that needs translation it is all done in config
* To update any translation the file in `locales/` need just to be updated and once save it will trigger new build
* We need to wrap all static text with `t()` and then represent all long words such as `Welcome to the world of UAE Open Data!` with short words so it can be easier to call and prevent errors during text matching to detect translation.

**Comment by demenech** [comment]
Really cool!
