### ISSUE TITLE
update Frontend app content layout to support RTL content flow

### ISSUE THREAD

**Issue by osahon-okungbowa** [FCSCOpendata/frontend#41]
We need to ensure that Frontend app's content layout can dynamically support RTL when the user switches to Arabic; And revert back to LTR when in English.

Anuar's Very Useful Comments on how to address this:

> If you want to add RTL support as well, here are few things to keep in mind while developing a React Native app:
> - Flexbox FTW — When you’re laying out your app, always use React Native’s flexbox because it gives you out of the box support for both LTR and RTL. For example, the flex-start property will align items to left in LTR, and to the right in RTL locales.
> - Absolute positioning — If you’re using absolute position in your app, don’t forget to align components to left or right, depending on the locale. In this case, you might want to use the isRTL variable we defined in our i18n.js file and apply left or right styles accordingly.
> - Menus — Another thing to keep in mind is the menus in your app, and more specifically, the drawer menu. You might want to change it’s opening direction for RTL languages.
> 
> Full article is here: https://medium.com/@danielsternlicht/adding-localization-i18n-g11n-to-a-react-native-project-with-rtl-support-223f39a8e6f2
> 

Tasks
- [x] content layout blocks flow from RTL dynamically when switched to Arabic.  This includes Left aligned Text, Label and UI Components
  - [x] Home page content layout and components flows RTL
  - [x] Dataset page content layout and components flows RTL
  - [x] Organisation page content layout and components flows RTL
  - [x] Topics page content layout and components flows RTL
  - [x] News page content layout and components flows RTL
  - [x] Header content layout and components flows RTL 
  - [x] Footer content layout and components flows RTL

**Comment by demenech** [comment]
- [ ] Resources Page
- [ ] Visualization Page
- [ ] Static Page/Post Pages

**Comment by demenech** [comment]
@osahon-okungbowa there might be still be some minor UI  issues.

**Comment by demenech** [comment]
PR: #51
