### ISSUE TITLE
update Frontend app dynamic content and labels to support both arabic and english

### ISSUE THREAD

**Issue by osahon-okungbowa** [FCSCOpendata/frontend#44]
All dynamic content pulled from CKAN into the frontend app needs to support Arabic as well as English when viewing the appropriate locale page

**Comment by demenech** [comment]
Issues:
- `package_search` doesn't return the organization translated title

**Comment by osahon-okungbowa** [comment]
@demenech just an FYI: dynamic content in this keywords/tag pill should also be translated. We have the pills on the Home Page, Dataset Metadata page etc . I think it's a component, then it will be easier to update)

![image](https://user-images.githubusercontent.com/60897650/187854021-095c0544-4988-4efe-8f5f-415e32e4e374.png)
![image](https://user-images.githubusercontent.com/60897650/187854408-7a52fef8-a617-4628-beda-9f15349b5efb.png)

**Comment by demenech** [comment]
PR: #58

**Comment by demenech** [comment]
: #66
